### ISSUE TITLE
Catch date links

### ISSUE THREAD

**Issue by kparal** [fedora-infra/mote#43]
In bugzilla, we have many comments like these:
```
Discussed at today's blocker review meeting [1].

This bug was rejected as blocker: This bug doesn't appear often enough to 
warrant blocking release. If this bug starts to show up on more platforms
please repropose.

[1] http://meetbot.fedoraproject.org/fedora-blocker-review/2015-05-18
```
It would be great if the historical links worked, if possible.  Currently they return 404. Thanks.

**Comment by kparal** [comment]
Sometimes we linked the directory, sometimes the particular txt/html file.

**Comment by Cydrobolt** [comment]
I'm going to work on this, hopefully get it fixed soon

**Comment by Cydrobolt** [comment]
Fixed in dbc9d33f4d913bdd7583bb865442e529a7e9a51a, will be pushed soon.

**Comment by Cydrobolt** [comment]
Deployed

**Comment by kparal** [comment]
Thanks.

**Comment by AdamWill** [comment]
Note, it still doesn't handle directories with a trailing slash. Compare http://meetbot.fedoraproject.org/fedora-blocker-review/2015-05-18 and http://meetbot.fedoraproject.org/fedora-blocker-review/2015-05-18/ .

**Comment by Cydrobolt** [comment]
Yeah, we haven't deployed the new patch yet.

**Comment by Cydrobolt** [comment]
There was another commit earlier that fixed the trailing slash thing.

**Comment by Cydrobolt** [comment]
Deployed fix for trailing slashes.
